// Importing the necessary parts from @langchain/google-genai
const { ChatGoogleGenerativeAI } = require('@langchain/google-genai');
require('dotenv').config();

/**
 * Summarize long-form text using Gemini 1.5 Flash via LangChain
 * @param {string} text - Extracted document or OCR text
 * @returns {Promise<string>} - A short summary
 */
async function summarizeText(text) {
    try {
        // Set up the Gemini 1.5 model from LangChain
        const model = new ChatGoogleGenerativeAI({
            model: 'gemini-2.0-flash',  // You can also try 'gemini-1.5-pro'
            apiKey: process.env.GOOGLE_API_KEY,
            maxOutputTokens: 2048,
            temperature: 0.6,
        });

        // Directly pass the user and system messages in the expected format
        const response = await model.call([
            { role: 'system', content: 'You are a helpful assistant that summarizes text concisely.' },
            { role: 'user', content: `Please summarize the following content:\n\n${text}` }
        ]);

        // Return the summary generated by the model
        return response.content;
    } catch (error) {
        console.error('❌ Gemini summarization failed:', error.message);
        throw new Error('Gemini summarization failed');
    }
}

module.exports = summarizeText;
